### ISSUE TITLE
[Bug] 331版本打包错误

### ISSUE THREAD

**Issue by DoveBoy** [LSPosed/LSPatch#109]
### Steps to reproduce/复现步骤

1.选择apk
2.选择模块
3.开始修补

### Expected behaviour/预期行为

生成修补后的apk

### Actual behaviour/实际行为

提示报错，无法修补任何apk
![Screenshot_2022-09-07-21-17-36-71_95dad6bc16335ca721bc2eca236c9ea6](https://user-images.githubusercontent.com/19201447/188890302-f296cf97-7250-4b5c-bea8-8c55691dc279.jpg)

### Xposed Module List/Xposed 模块列表

```Shell
杜比大喇叭
```

### LSPatch version/LSPatch 版本

0.3.1(330)

### Android version/Android 版本

13

### Shizuku version/Shizuku 版本

12.10.0

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPatch and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

![Screenshot_2022-09-07-21-19-12-29_95dad6bc16335ca721bc2eca236c9ea6](https://user-images.githubusercontent.com/19201447/188890119-5b51a13a-09ba-412b-9ded-1049aa487ba9.jpg)
![Screenshot_2022-09-07-21-17-36-71_95dad6bc16335ca721bc2eca236c9ea6](https://user-images.githubusercontent.com/19201447/188890157-5bba7d62-cf89-4c93-a9f9-205d0723dd09.jpg)

**Comment by jiasswee** [comment]
我也出现同样情况，请问解决了没有

**Comment by DoveBoy** [comment]
> 我也出现同样情况，请问解决了没有

没解决，试过Andorid13和10上面都这样

**Comment by zhanghua000** [comment]
https://t.me/QQUpdates/48
从这里下载的 QQ 安装包也是有一样的问题

**Comment by wqqwqqwqq** [comment]
安装支付宝一样的错误

**Comment by wqqwqqwqq** [comment]
安装支付宝一样的错误

**Comment by DoveBoy** [comment]
> 安装支付宝一样的错误

直接都没法打包，修补任何app都是这个错误

**Comment by JasonKhew96** [comment]
CI 测试版 无法复现，出现问题 的 请用 debug 版截图
https://github.com/LSPosed/LSPatch/actions/runs/3000497023

**Comment by DoveBoy** [comment]
> CI 测试版 无法复现，出现问题 的 请用 debug 版截图 https://github.com/LSPosed/LSPatch/actions/runs/3000497023

debug版修补同一app结果
![Screenshot_2022-09-19-19-31-24-04_95dad6bc16335ca721bc2eca236c9ea6](https://user-images.githubusercontent.com/19201447/191008314-51efa735-c823-4803-9520-58ca76953226.jpg)
![Screenshot_2022-09-19-19-31-51-64_95dad6bc16335ca721bc2eca236c9ea6](https://user-images.githubusercontent.com/19201447/191008327-6e13d368-95ae-481e-af81-b4430c3b9022.jpg)
Launch patch
, Attempt to invoke virtual method 'boolean java.lang.String.startsWith(java.lang.String)' on a null object reference
, java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.startsWith(java.lang.String)' on a null object reference
	at com.beust.jcommander.JCommander.expandArgs(JCommander.java:444)
	at com.beust.jcommander.JCommander.parse(JCommander.java:363)
	at com.beust.jcommander.JCommander.parse(JCommander.java:342)
	at org.lsposed.patch.LSPatch.<init>(LSPatch.java:120)
	at org.lsposed.lspatch.Patcher$patch$2.invokeSuspend(Patcher.kt:43)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

**Comment by zhanghua000** [comment]
debug 版以本地模式修补上文提到的 QQUpdates 频道提供的 QQ 安装包的结果
```
Launch patch
, Attempt to invoke virtual method 'boolean java.lang.String.startsWith(java.lang.String)' on a null object reference
, java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.startsWith(java.lang.String)' on a null object reference
	at com.beust.jcommander.JCommander.expandArgs(JCommander.java:444)
	at com.beust.jcommander.JCommander.parse(JCommander.java:363)
	at com.beust.jcommander.JCommander.parse(JCommander.java:342)
	at org.lsposed.patch.LSPatch.<init>(LSPatch.java:120)
	at org.lsposed.lspatch.Patcher$patch$2.invokeSuspend(Patcher.kt:43)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```
系统信息：
```
API 版本
93

LSPatch 版本
0.3.1 (330)

框架版本
1.8.3 (6600)

系统版本
10 (API 29)

设备
HUAWEI HONOR BKL-AL20 

系统架构
arm64-v8a
```

**Comment by DoveBoy** [comment]
> CI 测试版 无法复现，出现问题 的 请用 debug 版截图 https://github.com/LSPosed/LSPatch/actions/runs/3000497023

331依旧错误，无法修补任何app
```
API 版本
93

LSPatch 版本
0.3.1 (331)

框架版本
1.8.4 (6615)

系统版本
13 (API 33)

设备
OPPO PEEM00 

系统架构
arm64-v8a

```

```
Launch patch
, Attempt to invoke virtual method 'boolean java.lang.String.startsWith(java.lang.String)' on a null object reference
, java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.startsWith(java.lang.String)' on a null object reference
	at com.beust.jcommander.JCommander.expandArgs(JCommander.java:444)
	at com.beust.jcommander.JCommander.parse(JCommander.java:363)
	at com.beust.jcommander.JCommander.parse(JCommander.java:342)
	at org.lsposed.patch.LSPatch.<init>(LSPatch.java:120)
	at org.lsposed.lspatch.Patcher$patch$2.invokeSuspend(Patcher.kt:43)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

```

**Comment by zhanghua000** [comment]
使用 jar 程序完成打包可暂时绕过这个问题

**Comment by Dr-TSNG** [comment]
用这个然后复制报错信息
[manager-v0.3.1-331-debug.zip](https://github.com/LSPosed/LSPatch/files/9626030/manager-v0.3.1-331-debug.zip)

**Comment by DoveBoy** [comment]
> 用这个然后复制报错信息 [manager-v0.3.1-331-debug.zip](https://github.com/LSPosed/LSPatch/files/9626030/manager-v0.3.1-331-debug.zip)

用的就是debug版本打包的

**Comment by Howard20181** [comment]
@DoveBoy 加了额外的log，听开发者的

**Comment by yujincheng08** [comment]
不正常。我们会不知道你用的是 debug ci 版？既然知道我们为什么又发同一个版本让你抓日志？就是你在自以为是而已。

**Comment by DoveBoy** [comment]
> 用这个然后复制报错信息 [manager-v0.3.1-331-debug.zip](https://github.com/LSPosed/LSPatch/files/9626030/manager-v0.3.1-331-debug.zip)

```
API 版本
93

LSPatch 版本
0.3.1 (331)

框架版本
1.8.4 (6615)

系统版本
13 (API 33)

设备
OPPO PEEM00 

系统架构
arm64-v8a

```

```
Launch patch
, arg: %snull
, arg: %s-o
, arg: %s/data/user/0/org.lsposed.lspatch/cache/apk
, arg: %s-l
, arg: %s2
, arg: %s-v
, arg: %s-m
, arg: %s/data/app/~~w-pUyPz1kluvgOSrdZ5vLg==/com.raincat.dolby_beta-OqVAzgCR3ofk1Oaw8NW_2g==/base.apk
, Attempt to invoke virtual method 'boolean java.lang.String.startsWith(java.lang.String)' on a null object reference
, java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.startsWith(java.lang.String)' on a null object reference
	at com.beust.jcommander.JCommander.expandArgs(JCommander.java:444)
	at com.beust.jcommander.JCommander.parse(JCommander.java:363)
	at com.beust.jcommander.JCommander.parse(JCommander.java:342)
	at org.lsposed.patch.LSPatch.<init>(LSPatch.java:123)
	at org.lsposed.lspatch.Patcher$patch$2.invokeSuspend(Patcher.kt:43)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

```

**Comment by DoveBoy** [comment]
> 不正常。我们会不知道你用的是 debug ci 版？既然知道我们为什么又发同一个版本让你抓日志？就是你在自以为是而已。

我怎么知道你为什么发个名字一样的包？自己表述都不清楚，怪别人理解错误？难道每个人下载文件后都去核对md5？

**Comment by yujincheng08** [comment]
名字一样有什么问题。编译生成的，还得给你改名字？还不是你自己自以为是瞎理解

**Comment by Dr-TSNG** [comment]
> > 不正常。我们会不知道你用的是 debug ci 版？既然知道我们为什么又发同一个版本让你抓日志？就是你在自以为是而已。
> 
> 我怎么知道你为什么发个名字一样的包？自己表述都不清楚，怪别人理解错误？难道每个人下载文件后都去核对md5？

我们用同样的方式发过无数个包，你是第一个理解错误的

**Comment by DoveBoy** [comment]
> 名字一样有什么问题。编译生成的，还得给你改名字？还不是你自己自以为是瞎理解

可以不用改名字，回帖时多打几个字，注明增加log，你手指会断？

**Comment by yujincheng08** [comment]
会。

**Comment by DoveBoy** [comment]
> 会。

那我没话说了，跟个手指残废的人没什么好争执的了

**Comment by yujincheng08** [comment]
好，那 lock。

**Comment by canyie** [comment]
莫名其妙，又不是我们求着你修。
