### ISSUE TITLE
[Bug] 无法修补已修补的应用

### ISSUE THREAD

**Issue by jiwangyihao** [LSPosed/LSPatch#137]
### Steps to reproduce/复现步骤

1. 使用0.5.1-360修补任意应用
2. 再次修补刚刚输出的APK

### Expected behaviour/预期行为

正常修补（https://github.com/LSPosed/LSPatch/commit/279e95b57bffda5b7feb3ddce61c98269b5c6c94 中已添加了再次修补的支持）

### Actual behaviour/实际行为

修补失败

### Xposed Module List/Xposed 模块列表

```Shell
N/A
```

### LSPatch version/LSPatch 版本

0.5.1-360

### Android version/Android 版本

jar

### Shizuku version/Shizuku 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPatch and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

PS C:\Users\34404\Desktop> java -jar lspatch.jar -f -v C:\Users\34404\Desktop\xbrowser-release-360-lspatched.apk
Processing C:\Users\34404\Desktop\xbrowser-release-360-lspatched.apk -> C:\Users\34404\Desktop\.\xbrowser-release-360-lspatched-360-lspatched.apk
apk path: C:\Users\34404\Desktop\xbrowser-release-360-lspatched.apk
Parsing original apk...
Exception in thread "main" java.io.IOException: Failed to read zip file 'C:\Users\34404\Desktop\xbrowser-release-360-lspatched.apk'.
        at com.android.tools.build.apkzlib.zip.ZFile.<init>(ZFile.java:485)
        at com.android.tools.build.apkzlib.zip.NestedZip.<init>(NestedZip.java:17)
        at com.android.tools.build.apkzlib.zip.ZFile.addNestedZip(ZFile.java:1787)
        at org.lsposed.patch.LSPatch.patch(LSPatch.java:180)
        at org.lsposed.patch.LSPatch.doCommandLine(LSPatch.java:165)
        at org.lsposed.patch.LSPatch.main(LSPatch.java:140)
Caused by: java.io.IOException: Cannot read entry 'assets/lspatch/origin.apk' (offset: 1013, size: 1091901) because it overlaps with 'assets/about.html' (offset: 29628, size: 1116)
        at com.android.tools.build.apkzlib.zip.ZFile.readData(ZFile.java:701)
        at com.android.tools.build.apkzlib.zip.ZFile.<init>(ZFile.java:470)
        ... 5 more

**Comment by Dr-TSNG** [comment]
Expected

**Comment by jiwangyihao** [comment]
> Expected

意思是这个错误开发组已经预料到了吗？
之后会修复吗？
