### ISSUE TITLE
[Bug] crash by java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.app.Application.getApplicationContext()' on a null object reference

### ISSUE THREAD

**Issue by choday** [LSPosed/LSPatch#162]
### Steps to reproduce/复现步骤

install normal and click to start app
xiaomi 13
miui14.0.9
android 13

### Expected behaviour/预期行为

launch app success

### Actual behaviour/实际行为

crashed

### Xposed Module List/Xposed 模块列表

```Shell
none
```

### LSPatch version/LSPatch 版本

0.5.1(363)

### Android version/Android 版本

13

### Shizuku version/Shizuku 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPatch and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

FATAL EXCEPTION: main
                                                                                                    Process: com.ss.android.ugc.aweme, PID: 29318
                                                                                                    java.lang.ExceptionInInitializerError
                                                                                                    	at org.lsposed.lspatch.metaloader.LSPAppComponentFactoryStub.<clinit>(Unknown Source:420)
                                                                                                    	at java.lang.Class.newInstance(Native Method)
                                                                                                    	at android.app.LoadedApk.createAppFactory(LoadedApk.java:282)
                                                                                                    	at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:1052)
                                                                                                    	at android.app.LoadedApk.getClassLoader(LoadedApk.java:1139)
                                                                                                    	at android.app.LoadedApk.getResources(LoadedApk.java:1398)
                                                                                                    	at android.app.ContextImpl.createAppContext(ContextImpl.java:3100)
                                                                                                    	at android.app.ContextImpl.createAppContext(ContextImpl.java:3092)
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6939)
                                                                                                    	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2207)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:210)
                                                                                                    	at android.os.Looper.loop(Looper.java:299)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8235)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
                                                                                                    Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.app.Application.getApplicationContext()' on a null object reference
                                                                                                    	at android.os.TurboSchedMonitorImpl.getCurrentPackageName(TurboSchedMonitorImpl.java:507)
                                                                                                    	at android.os.TurboSchedMonitorImpl.isCoreApp(TurboSchedMonitorImpl.java:645)
                                                                                                    	at android.os.TurboSchedMonitorImpl.checkBoostPermission(TurboSchedMonitorImpl.java:188)
                                                                                                    	at android.os.TurboSchedMonitorImpl.triggerBoostAction(TurboSchedMonitorImpl.java:167)
                                                                                                    	at android.view.LayoutInflater.inflate(LayoutInflater.java:660)
                                                                                                    	at android.view.LayoutInflater.inflate(LayoutInflater.java:548)
                                                                                                    	at android.view.LayoutInflater.inflate(LayoutInflater.java:486)
                                                                                                    	at android.widget.ToastPresenter.getTextToastView(ToastPresenter.java:63)
                                                                                                    	at android.widget.Toast.makeText(Toast.java:504)
                                                                                                    	at android.widget.Toast.makeText(Toast.java:486)
                                                                                                    	at org.lsposed.lspatch.service.RemoteApplicationService.<init>(RemoteApplicationService.java:79)
                                                                                                    	at org.lsposed.lspatch.loader.LSPApplication.onLoad(LSPApplication.java:82)
                                                                                                    	at java.lang.Runtime.nativeLoad(Native Method)
                                                                                                    	at java.lang.Runtime.nativeLoad(Runtime.java:1121)
                                                                                                    	at java.lang.Runtime.load0(Runtime.java:927)
                                                                                                    	at java.lang.System.load(System.java:1625)
                                                                                                    	at org.lsposed.lspatch.metaloader.LSPAppComponentFactoryStub.<clinit>(Unknown Source:370)
                                                                                                    	at java.lang.Class.newInstance(Native Method) 
                                                                                                    	at android.app.LoadedApk.createAppFactory(LoadedApk.java:282) 
                                                                                                    	at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:1052) 
                                                                                                    	at android.app.LoadedApk.getClassLoader(LoadedApk.java:1139) 
                                                                                                    	at android.app.LoadedApk.getResources(LoadedApk.java:1398) 
                                                                                                    	at android.app.ContextImpl.createAppContext(ContextImpl.java:3100) 
                                                                                                    	at android.app.ContextImpl.createAppContext(ContextImpl.java:3092) 
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6939) 
                                                                                                    	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2207) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:210) 
                                                                                                    	at android.os.Looper.loop(Looper.java:299) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8235) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)

**Comment by Dr-TSNG** [comment]
No enough information
