### ISSUE TITLE
An error occurred in the update loader after updating to version 0.5.1-367[Bug] 

### ISSUE THREAD

**Issue by XJChenYang** [LSPosed/LSPatch#169]
### Steps to reproduce/复现步骤

In the integrated mode, click directly to update the loader, and after a short wait, an update error is displayed.

### Expected behaviour/预期行为

The update is successful, jump to the installation interface.

### Actual behaviour/实际行为

The update failed and an error message popped up.

### Xposed Module List/Xposed 模块列表

```Shell
QTool,QAuxiliary,TSbattery,XAutodaily
```

### LSPatch version/LSPatch 版本

0.5.1-367

### Android version/Android 版本

13

### Shizuku version/Shizuku 版本

13.0.0.r946.4cc584a (946)

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPatch and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

java.lang.RuntimeException: Binder invocation to an incorrect interface
java.lang.SecurityException: Binder invocation to an incorrect interface
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3025)
	at android.os.Parcel.createException(Parcel.java:3009)
	at android.os.Parcel.readException(Parcel.java:2992)
	at android.os.Parcel.readException(Parcel.java:2934)
	at android.content.pm.IPackageManager$Stub$Proxy.getPackageInstaller(IPackageManager.java:7565)
	at androidx.compose.ui.platform.a1.h(Unknown Source:18)
	at b7.h.getValue(Unknown Source:17)
	at v8.p.a(Unknown Source:2)
	at v8.o.a(Unknown Source:11)
	at v8.o.h(Unknown Source:0)
	at b7.h.getValue(Unknown Source:17)
	at v8.p.b(Unknown Source:2)
	at v8.i.i(Unknown Source:64)
	at v8.i.F(Unknown Source:12)
	at k2.o.a0(Unknown Source:4)
	at z.c1.k0(Unknown Source:71)
	at v8.l.f(Unknown Source:87)
	at t8.j.i(Unknown Source:350)
	at g7.a.o(Unknown Source:5)
	at v7.d0.run(Unknown Source:107)
	at kotlinx.coroutines.internal.e.run(Unknown Source:11)
	at kotlinx.coroutines.scheduling.i.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.a.run(Unknown Source:76)
Caused by: android.os.RemoteException: Remote stack trace:
	at android.os.Parcel.nativeEnforceInterface(Native Method)
	at android.os.Parcel.enforceInterface(Parcel.java:932)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:2177)
	at com.android.server.pm.PackageManagerService$IPackageManagerImpl.onTransact(PackageManagerService.java:6532)
	at android.os.Binder.execTransactInternal(Binder.java:1300)

**Comment by Dr-TSNG** [comment]
Try downgrade shizuku

**Comment by XJChenYang** [comment]
ok i will try now

Nullptr ***@***.***> 于 2023年1月28日周六 13:18写道：

**Comment by XJChenYang** [comment]
Thanks for knowing, now there is no error

Nullptr ***@***.***> 于 2023年1月28日周六 13:18写道：

**Comment by yujincheng08** [comment]
@RikkaW

**Comment by RikkaW** [comment]
https://github.com/RikkaApps/Shizuku/actions/runs/4030462993 Try this build

**Comment by XJChenYang** [comment]
I just tried it, this version of shizuku is fine.

Rikka ***@***.***> 于 2023年1月28日周六 14:02写道：
