### ISSUE TITLE
[Bug] Patched apk Manifest malformed

### ISSUE THREAD

**Issue by Howard20181** [LSPosed/LSPatch#170]
### Steps to reproduce/复现步骤

1. Patch an apk using `java -jar jar-v0.5.1-361-release.jar 拼多多_6.45.0.apk`
1. Install output apk

### Expected behaviour/预期行为

Install successfully

### Actual behaviour/实际行为

Failure [INSTALL_PARSE_FAILED_MANIFEST_MALFORMED: Failed parse during installPackageLI: /data/app/vmdl1067767559.tmp/base.apk (at Binary XML file line #93): android.content.IntentFilter$MalformedMimeTypeException: xmg.mobilebase.kenit.loader.hotplug.ActivityStubs$STDStub_00]

### Xposed Module List/Xposed 模块列表

```Shell
N/A
```

### LSPatch version/LSPatch 版本

368

### Android version/Android 版本

Android 13

### Shizuku version/Shizuku 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPatch and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

<details>

```
01-28 16:12:46.101  1982  2757 W AppIntegrityManagerServiceImpl: Exception reading file:///data/app/vmdl1076112839.tmp
01-28 16:12:46.101  1982  2757 W AppIntegrityManagerServiceImpl: com.android.server.pm.PackageManagerException: /data/app/vmdl1076112839.tmp/base.apk (at Binary XML file line #93): android.content.IntentFilter$MalformedMimeTypeException: xmg.mobilebase.kenit.loader.hotplug.ActivityStubs$STDStub_00
01-28 16:12:46.101  1982  2757 W AppIntegrityManagerServiceImpl: 	at com.android.server.pm.parsing.PackageParser2.parsePackage(PackageParser2.java:172)
01-28 16:12:46.101  1982  2757 W AppIntegrityManagerServiceImpl: 	at com.android.server.pm.parsing.PackageParser2.parsePackage(PackageParser2.java:150)
01-28 16:12:46.101  1982  2757 W AppIntegrityManagerServiceImpl: 	at com.android.server.integrity.AppIntegrityManagerServiceImpl.getPackageArchiveInfo(AppIntegrityManagerServiceImpl.java:624)
01-28 16:12:46.101  1982  2757 W AppIntegrityManagerServiceImpl: 	at com.android.server.integrity.AppIntegrityManagerServiceImpl.handleIntegrityVerification(AppIntegrityManagerServiceImpl.java:300)
01-28 16:12:46.101  1982  2757 W AppIntegrityManagerServiceImpl: 	at com.android.server.integrity.AppIntegrityManagerServiceImpl.-$$Nest$mhandleIntegrityVerification(Unknown Source:0)
01-28 16:12:46.101  1982  2757 W AppIntegrityManagerServiceImpl: 	at com.android.server.integrity.AppIntegrityManagerServiceImpl$1.lambda$onReceive$0$com-android-server-integrity-AppIntegrityManagerServiceImpl$1(AppIntegrityManagerServiceImpl.java:183)
01-28 16:12:46.101  1982  2757 W AppIntegrityManagerServiceImpl: 	at com.android.server.integrity.AppIntegrityManagerServiceImpl$1$$ExternalSyntheticLambda0.run(Unknown Source:4)
01-28 16:12:46.101  1982  2757 W AppIntegrityManagerServiceImpl: 	at android.os.Handler.handleCallback(Handler.java:942)
01-28 16:12:46.101  1982  2757 W AppIntegrityManagerServiceImpl: 	at android.os.Handler.dispatchMessage(Handler.java:99)
01-28 16:12:46.101  1982  2757 W AppIntegrityManagerServiceImpl: 	at android.os.Looper.loopOnce(Looper.java:201)
01-28 16:12:46.101  1982  2757 W AppIntegrityManagerServiceImpl: 	at android.os.Looper.loop(Looper.java:288)
01-28 16:12:46.101  1982  2757 W AppIntegrityManagerServiceImpl: 	at android.os.HandlerThread.run(HandlerThread.java:67)
01-28 16:12:46.102  1982  2757 W AppIntegrityManagerServiceImpl: Cannot parse package com.xunmeng.pinduoduo
01-28 16:12:46.102  1982  2434 I PackageManager: Integrity check passed for file:///data/app/vmdl1076112839.tmp
01-28 16:12:46.142  1982  2434 W PackageManager: Failed parse during installPackageLI: /data/app/vmdl1076112839.tmp/base.apk (at Binary XML file line #93): android.content.IntentFilter$MalformedMimeTypeException: xmg.mobilebase.kenit.loader.hotplug.ActivityStubs$STDStub_00
01-28 16:12:46.168  1982  2434 D PackageInstallerSession: Marking session 1076112839 as failed: INSTALL_PARSE_FAILED_MANIFEST_MALFORMED: Failed parse during installPackageLI: /data/app/vmdl1076112839.tmp/base.apk (at Binary XML file line #93): android.content.IntentFilter$MalformedMimeTypeException: xmg.mobilebase.kenit.loader.hotplug.ActivityStubs$STDStub_00
```
</details>

**Comment by harshitshah4** [comment]
Hey @Howard20181 can you please share the apk ?

**Comment by yujincheng08** [comment]
May have fixed by 5d8645d201154c9ee420a8a630c4f460111f0703

**Comment by Howard20181** [comment]
> Hey @Howard20181 can you please share the apk ?

https://mega.nz/file/vMNUjCAC#mPRbEoiMsL_cKi-ujNB0PsOl9PFyT2GYt27UaGH4h38
