### ISSUE TITLE
[Bug] 仅修补QQ出现的问题

### ISSUE THREAD

**Issue by lwbww** [LSPosed/LSPatch#171]
### Steps to reproduce/复现步骤

对QQ进行内嵌修补

### Expected behaviour/预期行为

应该修补成功

### Actual behaviour/实际行为

Launch patch
, Processing /data/user/0/org.lsposed.lspatch/cache/apk/QQ.apk -> /data/user/0/org.lsposed.lspatch/cache/apk/QQ-360-lspatched.apk
, apk path: /data/user/0/org.lsposed.lspatch/cache/apk/QQ.apk
, Parsing original apk...
, Register apk signer with default keystore...
, Original signature
30820253308201bca00302010202044bbb0361300d06092a864886f70d0101050500306d310e300c060355040613054368696e61310f300d06035504080c06e58c97e4baac310f300d06035504070c06e58c97e4baac310f300d060355040a0c06e885bee8aeaf311b3019060355040b0c12e697a0e7babfe4b89ae58aa1e7b3bbe7bb9f310b30090603550403130251513020170d3130303430363039343831375a180f32323834303132303039343831375a306d310e300c060355040613054368696e61310f300d06035504080c06e58c97e4baac310f300d06035504070c06e58c97e4baac310f300d060355040a0c06e885bee8aeaf311b3019060355040b0c12e697a0e7babfe4b89ae58aa1e7b3bbe7bb9f310b300906035504031302515130819f300d06092a864886f70d010101050003818d0030818902818100a15e9756216f694c5915e0b529095254367c4e64faeff07ae13488d946615a58ddc31a415f717d019edc6d30b9603d3e2a7b3de0ab7e0cf52dfee39373bc472fa997027d798d59f81d525a69ecf156e885fd1e2790924386b2230cc90e3b7adc95603ddcf4c40bdc72f22db0f216a99c371d3bf89cba6578c60699e8a0d536950203010001300d06092a864886f70d01010505000381810094a9b80e80691645dd42d6611775a855f71bcd4d77cb60a8e29404035a5e00b21bcc5d4a562482126bd91b6b0e50709377ceb9ef8c2efd12cc8b16afd9a159f350bb270b14204ff065d843832720702e28b41491fbc3a205f5f2f42526d67f17614d8a974de6487b2c866efede3b4e49a0f916baa3c1336fd2ee1b1629652049
, original appComponentFactory class: androidx.core.app.CoreComponentFactory
, Patching apk...
, Adding config...
, Adding metaloader dex...
, Adding loader dex...
, Adding native lib...
, added assets/lspatch/so/x86_64/liblspatch.so
, added assets/lspatch/so/x86/liblspatch.so
, added assets/lspatch/so/armeabi-v7a/liblspatch.so
, added assets/lspatch/so/arm64-v8a/liblspatch.so
, Embedding modules...
,   - io.github.qauxv
, Creating nested apk link...
, Writing apk...
, /data/user/0/org.lsposed.lspatch/cache/tempdir_7785263646091900782/temp_4649284995494064410.data: open failed: ENOENT (No such file or directory)
, java.io.FileNotFoundException: /data/user/0/org.lsposed.lspatch/cache/tempdir_7785263646091900782/temp_4649284995494064410.data: open failed: ENOENT (No such file or directory)
	at libcore.io.IoBridge.open(IoBridge.java:574)
	at java.io.FileInputStream.<init>(FileInputStream.java:160)
	at c6.f.j(Unknown Source:26)
	at a5.b.j(Unknown Source:4)
	at v4.k.j(Unknown Source:34)
	at c6.q.a(Unknown Source:19)
	at c6.q.<init>(Unknown Source:8)
	at c6.f.j(Unknown Source:16)
	at a5.b.j(Unknown Source:4)
	at y4.y.S(Unknown Source:713)
	at y4.y.close(Unknown Source:4)
	at h9.a.a(Unknown Source:1008)
	at o8.b.j(Unknown Source:23)
	at l7.a.m(Unknown Source:5)
	at a8.d0.run(Unknown Source:105)
	at f8.e.run(Unknown Source:11)
	at g8.i.run(Unknown Source:2)
	at g8.a.run(Unknown Source:79)
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:274)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8234)
	at libcore.io.IoBridge.open(IoBridge.java:560)
	... 17 more

### Xposed Module List/Xposed 模块列表

```Shell
QAuxiliary_1.3.9.r1319.ce1fce4
```

### LSPatch version/LSPatch 版本

0051

### Android version/Android 版本

13

### Shizuku version/Shizuku 版本

12.14

### Version requirement/版本要求

- [ ] I am using latest debug CI version of LSPatch and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

<details>

```
# Replace this line with the log / 将此行用日志替换
```
</details>

**Comment by Howard20181** [comment]
不是最新CI版的
