### ISSUE TITLE
[Bug] invalid column original_mimetype

### ISSUE THREAD

**Issue by zsnjuts** [LSPosed/LSPatch#205]
### Steps to reproduce/复现步骤

1. 选择已安装的应用程序，选择微信
2. 勾选便携模式
3. 选择嵌入模块，选择WeChat Pad
4. 点击开始修补

### Expected behaviour/预期行为

修补完成后生成apk，日志显示正常

### Actual behaviour/实际行为

修补之后，拷贝apk时报错，报错日志附在后面了

### Xposed Module List/Xposed 模块列表

```Shell
WeChat Pad
```

### LSPatch version/LSPatch 版本

LSPatch版本0.5(348)；框架版本1.8.4(6615)

### Android version/Android 版本

10(API 29)

### Shizuku version/Shizuku 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPatch and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

<details>

```
Launch patch
, Processing /data/app/com.tencent.mm-kIQcLS3Q8j5EZI4mZK3irw==/base.apk -> /data/user/0/org.lsposed.lspatch/cache/apk/base-348-lspatched.apk
, apk path: /data/app/com.tencent.mm-kIQcLS3Q8j5EZI4mZK3irw==/base.apk
, Parsing original apk...
, Register apk signer with default keystore...
, Original signature
308202eb30820254a00302010202044d36f7a4300d06092a864886f70d01010505003081b9310b300906035504061302383631123010060355040813094775616e67646f6e673111300f060355040713085368656e7a68656e31353033060355040a132c54656e63656e7420546563686e6f6c6f6779285368656e7a68656e2920436f6d70616e79204c696d69746564313a3038060355040b133154656e63656e74204775616e677a686f7520526573656172636820616e6420446576656c6f706d656e742043656e7465723110300e0603550403130754656e63656e74301e170d3131303131393134333933325a170d3431303131313134333933325a3081b9310b300906035504061302383631123010060355040813094775616e67646f6e673111300f060355040713085368656e7a68656e31353033060355040a132c54656e63656e7420546563686e6f6c6f6779285368656e7a68656e2920436f6d70616e79204c696d69746564313a3038060355040b133154656e63656e74204775616e677a686f7520526573656172636820616e6420446576656c6f706d656e742043656e7465723110300e0603550403130754656e63656e7430819f300d06092a864886f70d010101050003818d0030818902818100c05f34b231b083fb1323670bfbe7bdab40c0c0a6efc87ef2072a1ff0d60cc67c8edb0d0847f210bea6cbfaa241be70c86daf56be08b723c859e52428a064555d80db448cdcacc1aea2501eba06f8bad12a4fa49d85cacd7abeb68945a5cb5e061629b52e3254c373550ee4e40cb7c8ae6f7a8151ccd8df582d446f39ae0c5e930203010001300d06092a864886f70d0101050500038181009c8d9d7f2f908c42081b4c764c377109a8b2c70582422125ce545842d5f520aea69550b6bd8bfd94e987b75a3077eb04ad341f481aac266e89d3864456e69fba13df018acdc168b9a19dfd7ad9d9cc6f6ace57c746515f71234df3a053e33ba93ece5cd0fc15f3e389a3f365588a9fcb439e069d3629cd7732a13fff7b891499
, original appComponentFactory class: androidx.core.app.CoreComponentFactory
, Patching apk...
, Adding config...
, Adding metaloader dex...
, Adding loader dex...
, Adding native lib...
, added assets/lspatch/so/x86_64/liblspatch.so
, added assets/lspatch/so/x86/liblspatch.so
, added assets/lspatch/so/armeabi-v7a/liblspatch.so
, added assets/lspatch/so/arm64-v8a/liblspatch.so
, Embedding modules...
,   - com.tencent.mm.forcepad
, Creating nested apk link...
, Writing apk...
, Done. Output APK: /data/user/0/org.lsposed.lspatch/cache/apk/base-348-lspatched.apk
, Invalid column original_mimetype
, java.lang.IllegalArgumentException: Invalid column original_mimetype
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:216)
	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:197)
	at android.content.ContentProviderProxy.openAssetFile(ContentProviderNative.java:649)
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1521)
	at android.content.ContentResolver.openOutputStream(ContentResolver.java:1227)
	at android.content.ContentResolver.openOutputStream(ContentResolver.java:1203)
	at t8.b.h(Unknown Source:222)
	at m7.a.l(Unknown Source:8)
	at c8.d0.run(Unknown Source:100)
	at h8.e.run(Unknown Source:11)
	at i8.i.run(Unknown Source:2)
	at i8.a.run(Unknown Source:79)

```
</details>

**Comment by yujincheng08** [comment]
`ContentResolver` 报错，是系统问题。
