### ISSUE TITLE
android 12 crashed

### ISSUE THREAD

**Issue by MAT-OUT** [LSPosed/LSPatch#31]
#######RuntimeEnvironmentInformation#######
crash time=2021-11-30 17:34:36.099
model=MI 9
android version=12(31)
brand=Xiaomi
manufacturer=Xiaomi
board=cepheus
hardware=qcom
device=cepheus
version name=6.50.0
supported ABIs=arm64-v8a & armeabi-v7a & armeabi
display=awaken_cepheus-userdebug 12 SD1A.210817.036.A8 1635968484 release-keys
#######ForceCloseCrashLog#######
FATAL EXCEPTION: main
Process: tv.danmaku.bili, PID: 21115
java.lang.RuntimeException: Unable to start activity ComponentInfo{tv.danmaku.bili/tv.danmaku.bili.MainActivityV2}: java.lang.RuntimeException: Unable to instantiate application bin.mt.apksignaturekillerplus.HookApplication package tv.danmaku.bili: java.lang.IllegalStateException: Plugins can't be changed anymore
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3635)
 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3792)
 at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
 at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
 at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210)
 at android.os.Handler.dispatchMessage(Handler.java:106)
 at android.os.Looper.loopOnce(Looper.java:201)
 at android.os.Looper.loop(Looper.java:288)
 at android.app.ActivityThread.main(ActivityThread.java:7839)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Caused by: java.lang.RuntimeException: Unable to instantiate application bin.mt.apksignaturekillerplus.HookApplication package tv.danmaku.bili: java.lang.IllegalStateException: Plugins can't be changed anymore
 at android.app.LoadedApk.makeApplication(LoadedApk.java:1364)
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3550)
 ... 12 more
Caused by: java.lang.IllegalStateException: Plugins can't be changed anymore
 at y2.b.a.e.a.B(Unknown Source:11)
 at tv.danmaku.bili.proc.task.b.b(Unknown Source:6)
 at tv.danmaku.bili.proc.task.j.a(Unknown Source:54)
 at tv.danmaku.bili.proc.u.c(Unknown Source:13)
 at tv.danmaku.bili.proc.MainBiliAppProcWrapper.c(Unknown Source:2)
 at com.bilibili.base.b.attachBaseContext(Unknown Source:62)
 at bin.mt.apksignaturekillerplus.HookApplication.attachBaseContext(Unknown Source:3)
 at android.app.Application.attach(Application.java:331)
 at android.app.Instrumentation.newApplication(Instrumentation.java:1180)
 at android.app.LoadedApk.makeApplication(LoadedApk.java:1356)
 ... 13 more

**Comment by yujincheng08** [comment]
Unable to instantiate application bin.mt.apksignaturekillerplus.HookApplication package

not our problem

**Comment by MAT-OUT** [comment]
> Unable to instantiate application bin.mt.apksignaturekillerplus.HookApplication package
> 
> not our problem

emm, Can I ask one more question and how to use -l, --sigbypasslv
       Signature bypass level. 0 (disable), 1 (pm), 2 (pm+openat). default 0
       Default: 0
it can‘t work...
