### ISSUE TITLE
android 12 确实闪退，请求查明原因

### ISSUE THREAD

**Issue by MAT-OUT** [LSPosed/LSPatch#32]
经安卓12真机测试，与hook去校验无关，现在用原包打包了，依旧闪退

FATAL EXCEPTION: main
Process: tv.danmaku.bili, PID: 31314
java.lang.RuntimeException: Unable to start activity ComponentInfo{tv.danmaku.bili/tv.danmaku.bili.MainActivityV2}: java.lang.RuntimeException: Unable to instantiate application tv.danmaku.bili.HiltApplication package tv.danmaku.bili: java.lang.IllegalStateException: Plugins can't be changed anymore
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3635)
 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3792)
 at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
 at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
 at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210)
 at android.os.Handler.dispatchMessage(Handler.java:106)
 at android.os.Looper.loopOnce(Looper.java:201)
 at android.os.Looper.loop(Looper.java:288)
 at android.app.ActivityThread.main(ActivityThread.java:7839)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Caused by: java.lang.RuntimeException: Unable to instantiate application tv.danmaku.bili.HiltApplication package tv.danmaku.bili: java.lang.IllegalStateException: Plugins can't be changed anymore
 at android.app.LoadedApk.makeApplication(LoadedApk.java:1364)
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3550)
 ... 12 more
Caused by: java.lang.IllegalStateException: Plugins can't be changed anymore
 at y2.b.a.e.a.B(BL:3)
 at tv.danmaku.bili.proc.task.b.b(BL:1)
 at tv.danmaku.bili.proc.task.j.a(BL:9)
 at tv.danmaku.bili.proc.u.c(BL:3)
 at tv.danmaku.bili.proc.MainBiliAppProcWrapper.c(BL:1)
 at com.bilibili.base.b.attachBaseContext(BL:9)
 at android.app.Application.attach(Application.java:331)
 at android.app.Instrumentation.newApplication(Instrumentation.java:1180)
 at android.app.LoadedApk.makeApplication(LoadedApk.java:1356)
 ... 13 more

**Comment by vvb2060** [comment]
tv.danmaku.bili 版本号 6510300，在Android12 的Pixel3和MIUI测试正常。

**Comment by yujincheng08** [comment]
雀食有概率复现

**Comment by yujincheng08** [comment]
```
12-08 17:38:42.059  9590  9590 E AndroidRuntime: Process: tv.danmaku.bili, PID: 9590
12-08 17:38:42.059  9590  9590 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{tv.danmaku.bili/tv.danmaku.bili.MainActivityV2}: java.lang.RuntimeException: Unable to instantiate application tv.danmaku.bili.HiltApplication package tv.danmaku.bili: java.lang.IllegalStateException: Plugins can't be changed anymore
12-08 17:38:42.059  9590  9590 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3747)
12-08 17:38:42.059  9590  9590 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3921)
12-08 17:38:42.059  9590  9590 E AndroidRuntime:        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
12-08 17:38:42.059  9590  9590 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
12-08 17:38:42.059  9590  9590 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
12-08 17:38:42.059  9590  9590 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2285)
12-08 17:38:42.059  9590  9590 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
12-08 17:38:42.059  9590  9590 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:210)
12-08 17:38:42.059  9590  9590 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:299)
12-08 17:38:42.059  9590  9590 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:8258)
12-08 17:38:42.059  9590  9590 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
12-08 17:38:42.059  9590  9590 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
12-08 17:38:42.059  9590  9590 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
12-08 17:38:42.059  9590  9590 E AndroidRuntime: Caused by: java.lang.RuntimeException: Unable to instantiate application tv.danmaku.bili.HiltApplication package tv.danmaku.bili: java.lang.IllegalStateException: Plugins can't be changed anymore
12-08 17:38:42.059  9590  9590 E AndroidRuntime:        at android.app.LoadedApk.makeApplication(LoadedApk.java:1377)
12-08 17:38:42.059  9590  9590 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3662)
12-08 17:38:42.059  9590  9590 E AndroidRuntime:        ... 12 more
12-08 17:38:42.059  9590  9590 E AndroidRuntime: Caused by: java.lang.IllegalStateException: Plugins can't be changed anymore
12-08 17:38:42.059  9590  9590 E AndroidRuntime:        at y2.b.a.e.a.B(BL:3)
12-08 17:38:42.059  9590  9590 E AndroidRuntime:        at tv.danmaku.bili.proc.task.b.b(BL:1)
12-08 17:38:42.059  9590  9590 E AndroidRuntime:        at tv.danmaku.bili.proc.task.j.a(BL:9)
12-08 17:38:42.059  9590  9590 E AndroidRuntime:        at tv.danmaku.bili.proc.u.c(BL:3)
12-08 17:38:42.059  9590  9590 E AndroidRuntime:        at tv.danmaku.bili.proc.MainBiliAppProcWrapper.c(BL:1)
12-08 17:38:42.059  9590  9590 E AndroidRuntime:        at com.bilibili.base.b.attachBaseContext(BL:9)
12-08 17:38:42.059  9590  9590 E AndroidRuntime:        at android.app.Application.attach(Application.java:333)
12-08 17:38:42.059  9590  9590 E AndroidRuntime:        at android.app.Instrumentation.newApplication(Instrumentation.java:1178)
12-08 17:38:42.059  9590  9590 E AndroidRuntime:        at android.app.LoadedApk.makeApplication(LoadedApk.java:1369)
12-08 17:38:42.059  9590  9590 E AndroidRuntime:        ... 13 more
```

**Comment by yujincheng08** [comment]
修好了
