### ISSUE TITLE
应用闪退问题

### ISSUE THREAD

**Issue by takoyakiwhite** [LSPosed/LSPatch#35]
系统版本：Magic UI 6.0 / Android 12
打包网易云，闪退

[02-13 00:30:14.416 19945:19945 E/LoadedApk]
Unable to instantiate appComponentFactory
java.lang.ClassNotFoundException: Didn't find class "" on path: DexPathList[[zip file "/data/user/0/com.netease.cloudmusic/cache/lspatch/origin/11870886"],nativeLibraryDirectories=[/data/app/~~GTQUqu0TWg9hK0SIxQ1Zng==/com.netease.cloudmusic-xB_qZ-FwE3C5H16QB6f6qw==/lib/arm64, /system/fake-libs64, /data/user/0/com.netease.cloudmusic/cache/lspatch/origin/11870886!/lib/arm64-v8a, /system/lib64, /product_h/lib64, /system_ext/lib64]]
 at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:218)
 at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
 at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
 at android.app.LoadedApk.createAppFactory(LoadedApk.java:276)
 at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:1098)
 at android.app.LoadedApk.getClassLoader(LoadedApk.java:1185)
 at org.lsposed.lspatch.loader.LSPLoader.initModules(LSPLoader.java:19)
 at org.lsposed.lspatch.loader.LSPApplication.onLoad(LSPApplication.java:113)
 at java.lang.Runtime.nativeLoad(Native Method)
 at java.lang.Runtime.nativeLoad(Runtime.java:1121)
 at java.lang.Runtime.load0(Runtime.java:927)
 at java.lang.System.load(System.java:1621)
 at org.lsposed.lspatch.appstub.LSPAppComponentFactoryStub.<clinit>(LSPAppComponentFactoryStub.java:38)
 at java.lang.Class.newInstance(Native Method)
 at android.app.LoadedApk.createAppFactory(LoadedApk.java:276)
 at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:1098)
 at android.app.LoadedApk.getClassLoader(LoadedApk.java:1185)
 at android.app.LoadedApk.getResources(LoadedApk.java:1463)
 at android.app.ContextImpl.createAppContext(ContextImpl.java:3196)
 at android.app.ContextImpl.createAppContext(ContextImpl.java:3184)
 at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7571)
 at android.app.ActivityThread.access$2700(ActivityThread.java:279)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2506)
 at android.os.Handler.dispatchMessage(Handler.java:109)
 at android.os.Looper.loopOnce(Looper.java:206)
 at android.os.Looper.loop(Looper.java:296)
 at android.app.ActivityThread.main(ActivityThread.java:8899)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:569)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:976)

**Comment by yujincheng08** [comment]
类名空了草

**Comment by takoyakiwhite** [comment]
希望大佬们能快点修复，可投食一波）听不了歌实在是太南了😢奈何对Android一窍不通

**Comment by yujincheng08** [comment]
进入我 github 个人页面可以看到 sponsor 按钮，点击即可投食

**Comment by moeshin** [comment]
我用两个月前的，打包其他应用貌似没啥问题 https://github.com/LSPosed/LSPatch/actions/runs/1554390421

**Comment by takoyakiwhite** [comment]
> 我用两个月前的，打包其他应用貌似没啥问题 https://github.com/LSPosed/LSPatch/actions/runs/1554390421

Android 12两个月前好像还不支持

**Comment by moeshin** [comment]
> > 我用两个月前的，打包其他应用貌似没啥问题 https://github.com/LSPosed/LSPatch/actions/runs/1554390421
> 
> Android 12两个月前好像还不支持

我看提交是有的，你试试吧

**Comment by takoyakiwhite** [comment]
> > > 我用两个月前的，打包其他应用貌似没啥问题 https://github.com/LSPosed/LSPatch/actions/runs/1554390421
> > 
> > Android 12两个月前好像还不支持
> 
> 我看提交是有的，你试试吧

明早试试，话说老哥我在TG找你有点事）

**Comment by takoyakiwhite** [comment]
使用舊版lspatch實測同報錯

**Comment by Dr-TSNG** [comment]
提供下网易云版本，我这儿无法复现

**Comment by Dr-TSNG** [comment]
5a16a34cd89729c7dc6c303868a0e6a87e3794d8
应该修好了，用最新ci试试
