### ISSUE TITLE
[Bug] Get the application name: null

### ISSUE THREAD

**Issue by Stillhard** [LSPosed/LSPatch#9]
The patch process finished, but can't run/install:
```
06-16 14:03:20.337  2655  2655 W System.err:    at org.lsposed.lspatch.loader.util.FileUtils.readTextFromAssets(FileUtils.java:32)
06-16 14:03:20.337  2655  2655 W System.err:    at org.lsposed.lspatch.loader.LSPApplication.<clinit>(LSPApplication.java:83)
06-16 14:03:20.337  2655  2655 W System.err:    at org.lsposed.lspatch.appstub.LSPApplicationStub.<clinit>(LSPApplicationStub.java:48)
```
Inside the modded apk I can only find 1 .ini file: original_signature_info.ini
I guess the error because it was trying to find the original_application_name.ini which failed earlier in the process
```
decompress apk cost time: 110ms
dexFileCount: 1
Get application name cost time: 31ms
Get the application name: null
Target app dont have lib/armeabi/, skip
```

**Comment by 327135569** [comment]
Fixed, Thank you!
